name: Test

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: test/go.mod

      - name: Run Terratest
        working-directory: test
        run: go test -v -timeout 30m
        env:
          AWS_REGION: us-east-1
